# Copyright © 2026 立方田 <managecode@gmail.com>
[package]
name = "data-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ime-data = { path = "../../crates/ime-data" }
ime-security = { path = "../../crates/ime-security" }
serde_json.workspace = true

[lints]
workspace = true
