[package]
name = "ime-security"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chacha20poly1305 = "0.11.0"
ed25519-dalek = "3.0.0"
getrandom = "0.4.3"
ime-data = { path = "../ime-data" }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.11.0"

[lints]
workspace = true
