#!/usr/bin/env python3
# Copyright © 2026 立方田 <managecode@gmail.com>
"""Generate the Rime overlay from the project's single maintained TSV source."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'crates/ime-engine-pinyin/data/curated_phrase_lexicon.tsv'
DESTINATION = ROOT / 'platform/android-ime/app/src/main/assets/rime/zhimo_curated.dict.yaml'


def render(source, version):
    rows, seen = [], set()
    for line in source.splitlines():
        if not line or line.startswith('#'):
            continue
        reading, word, weight = line.split('\t')
        if (reading, word) in seen or int(weight) <= 0:
            raise ValueError('duplicate phrase or invalid weight')
        if len(reading.split()) != len(word):
            raise ValueError('reading/character count mismatch')
        seen.add((reading, word))
        rows.append(f'{word}\t{reading}\t{weight}\n')
    return ('# Copyright © 2026 立方田 <managecode@gmail.com>\n'
            '# Generated by tools/sync-curated-lexicon.py; edit curated_phrase_lexicon.tsv.\n'
            f'---\nname: zhimo_curated\nversion: "{version}"\nsort: by_weight\n...\n' + ''.join(rows))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    version = (DESTINATION.parent / 'version.txt').read_text().strip()
    expected = render(SOURCE.read_text(), version)
    if args.check:
        if DESTINATION.read_text() != expected:
            raise SystemExit('Curated Rime dictionary is stale; run tools/sync-curated-lexicon.py')
    else:
        DESTINATION.write_text(expected, encoding='utf-8')


if __name__ == '__main__':
    main()
