[package]
name = "ime-engine-rime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[features]
default = []
native-librime = []

[dependencies]
ime-core = { path = "../ime-core" }

[build-dependencies]
cc = "1.2"

[lints.rust]
unsafe_code = "allow"
